language: android
jdk : openjdk7

before_install:
 - chmod +x gradlew
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

  components:
    - build-tools-22.0.1
    -sys-img-armeabi-v7a-android-22

  licences:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - ./gradlew :GiglioOnlus:clean :GiglioOnlus:build
    #- ls /home/travis/build/kul3r4/droidConf/londonWeather/build/outputs/apk/londonWeather-debug.apk
    #- ./gradlew :londonWeatherAcceptance:test --stacktrace --debug -DANDROID_HOME=/usr/local/android-sdk/
